name: mangroves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - torchvision
  - torchmetrics
  - lightning
  - scikit-learn
  - scikit-image
  - matplotlib
  - numpy
  - pandas
  - python-dateutil
  - earthengine-api
  - ipykernel
  - tqdm
  - geopandas
  - ruamel.yaml
  - rasterio