name: mangroves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - pyproj
  - numpy
  - pandas
  - python-dateutil
  - earthengine-api
  - ipykernel
  - tqdm
  - geopandas