litmodule_options:
  optimizers:
    name: 'Adam'
    parameters:
      lr: 1e-3
      weight_decay: 1e-5
  lr_schedulers:
    name: 'StepLR'
    parameters:
      step_size: 10
      gamma: 0.1
  # checkpoint_path: ''
  parameters:
    num_classes: 6

model_options:
  model_class: "Classifier"
  parameters:
    in_channels: 64
    out_features: 6