hyperparameters:
  max_epochs: 1
  log_every_n_steps: 100
  accelerator: "gpu"
  strategy: "auto"
  devices: 1
callbacks:
  name: ['ModelCheckpoint', 'LearningRateMonitor']
  parameters: [{monitor: "val_loss", save_last: True, save_top_k: 1}, {logging_interval: "step"}]
logger:
  name: 'TensorBoardLogger'
  parameters: {save_dir: "~/owl/logs/"}